%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    C:\Users\mufasa\Documents\Thesis\hardware\probeCalibration\Probe
%    Calibrations\13058-1_M205_RawData.xlsx Worksheet: 13058-1_M205
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2013/08/01 18:00:25

%% Import the data
[data, ~, raw] = xlsread('C:\Users\mufasa\Documents\Thesis\hardware\probeCalibration\Probe Calibrations\13058-1_M205_RawData.xlsx','13058-1_M205','A15:L596');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,3,4,5,6,7,8,9,10,11,12]);
raw = raw(:,2);

%% Create output variable
%data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Thetadeg = data(:,1);
Phideg = data(:,1);
P1Torr = data(:,2);
P2Torr = data(:,3);
P3Torr = data(:,4);
P4Torr = data(:,5);
P5Torr = data(:,6);
P6Torr = data(:,7);
PtTorr = data(:,8);
PsAbsTorr = data(:,9);
TsC = data(:,10);
PrefAbsTorr = data(:,11);

%% Clear temporary variables
clearvars data raw cellVectors;