function [xAxis,yAxis,xUnit,yUnit] = getAxisNames(handles)
    xAxisVarName = get(handles.xAxisVar,'String');
    xAxis = char(xAxisVarName(get(handles.xAxisVar,'Value')));
    xUnit = handles.data.(xAxis).units;
%     xUnit = char(handles.units(get(handles.xAxisVar,'Value')));
    yAxisVarName = get(handles.yAxisVar,'String');
    yAxis = char(yAxisVarName(get(handles.yAxisVar,'Value')));
%     yUnit = char(handles.units(get(handles.yAxisVar,'Value')));
        yUnit = handles.data.(yAxis).units;